atom/fuzzy-finder

lib/load-paths-handler.coffee
spec/fuzzy-finder-spec.coffee

This will only follow symlinks outside the root directory, removing duplicates in the results:
Before 
After

Do not follow symlinks internal to the root directory

---

lib/load-paths-handler.coffee
lib/main.coffee
lib/path-loader.coffee
lib/project-view.coffee
spec/fuzzy-finder-spec.coffee

This currently has the issue of the linked files showing up twice.

Use core.followSymlinks rather than the fuzzy-finder specific option

---

keymaps/fuzzy-finder.cson
lib/fuzzy-finder-view.coffee
lib/main.coffee
spec/fuzzy-finder-spec.coffee

Fixes #34: Add feature to search through all open panes instead of just the active one, a preference to control this, and the ability to invert the current preference with Shift-Enter.
@izuzak Sorry about creating a second PR, I got confused about how to rebase and screwed up the other branch.

Add feature to search through all open panes instead of just active pane

---

lib/fuzzy-finder-view.coffee
lib/main.coffee
spec/fuzzy-finder-spec.coffee

When working, I love having minimal number of opened tabs. Thus, I close and open files all the time. This is kinda ingrained habit for me. I'm really used to flow of JetBrains products, because their fuzzy search remembers a query string of your previous search.
Lack of this option was always a deal breaker for me. But since Atom is so hackable, it was just few lines of code to make it work. What's your opinion on it?
Here's a gif where I show pain of typing same query string two times. And then, after enabling this option where you can see the preserved query string so I can open file instantly. From this example it might seem I'm not aware of undo close tab shortcut. This is not the case. 
Better way to describe problem that this feature solves is that on our projects we have lots of …

Add option to preserve last search query

---

lib/fuzzy-finder-view.coffee
lib/main.coffee
package.json

As per this discussion first step is testing new scoring algorithm as an option (disabled by default)
https://github.com/atom/fuzzaldrin/pull/22#issuecomment-142701468

Optionally allow to use some improvement to fuzzaldrin.

---

lib/project-view.coffee
spec/fuzzy-finder-spec.coffee

The previous code wasn’t returning `data` correctly if the last opened path was not found in the list, leading to the behavior pictured above. Basically if you switched away from an editor that was outside the project to a new editor, than toggled the fuzzy-finder, you'd see that screenshot.
/cc @joshaber for awareness but with :heart:.

Return project paths correctly if last-opened path is not in project

---

lib/fuzzy-finder-view.coffee

In https://github.com/atom/atom/pull/7953, we changed the default pane splitting key bindings to dispatch `pane:split-*-and-copy-active-item` rather than the existing `pane-split-*` commands. Unfortunately, we forgot to handle these command variants in the fuzzy finder, which broke the "split open" workflow.
Closes #190
/cc @technoweenie

Handle all variations of pane splitting commands

---

lib/fuzzy-finder-view.coffee
lib/project-view.coffee
spec/fuzzy-finder-spec.coffee

Fixes #188.
I don’t love how this turned out. The problem is that getting git status is async now, but the view needs to be created synchronously. I’m not sure if there’s a better way to accomplish this.
/cc @atom/core

Fix slow opening

---

lib/load-paths-handler.coffee

Fixes https://github.com/atom/fuzzy-finder/issues/111.
If the repository was embedded in another repository, then the inner repository itself could be ignored which meant we wouldn’t index anything.
This _might_ be less than ideal in that project roots which were previously entirely ignored now won’t be. But I gotta think that if you opened a project root, you don’t want the whole project ignored.

Don't ignore the whole project.

---

lib/project-view.coffee
spec/fuzzy-finder-spec.coffee

This fixes #196 and its dupes - if a network drive goes away, we were crashing while trying to get a realpath for the project. This just catches ENOENT and shows the user an error message rather than raising an uncaught error - not a big behavior change, but catching is better than not catching, eh?
@atom/feedback do you feel this is sufficient to address that problem?

Catch ENOENT when reloading paths

---

lib/fuzzy-finder-view.coffee

Full explanation can be found here: atom/tabs#359.
This is essentially just a housekeeping PR to ensure all packages consuming this service behave consistently with each other. Nothing new is being added functionality-wise.
/cc @as-cii

Declare calling context for icon-service providers

---

spec/fuzzy-finder-spec.coffee

atom/atom#13977 adds multiple pane locations and updates the
`atom.workspace.getPanes()` API to return the panes from all of them.
This fixes the resultant test failures by only checking the panes in
the center.

Only check panes in center

---

lib/buffer-view.js
lib/git-status-view.js
lib/project-view.js

Fixes #288.
Previously, we were waiting until the items had been populated before showing the fuzzy finder. However, this was causing an odd UX experience that made users accidentally type query characters into already opened buffers.
With this pull request, on toggle, we will show the fuzzy finder synchronously and only then request an animation frame where we populate the items.
/cc: @atom/maintainers

Don't wait for items to be updated before showing fuzzy finder

---

lib/fuzzy-finder-view.js

Fixes #296.
/cc: @jeancroy @50Wliu

Show matches correctly when `useAlternateScoring` is true

---

spec/fuzzy-finder-spec.coffee

Now that the stable release of Atom includes atom/atom#13977, we no longer need this shim.
---
xref: https://github.com/atom/fuzzy-finder/pull/283 (which introduced this shim)

Remove obsolete shim for atom.workspace.getCenter()

---

lib/load-paths-handler.js
spec/fuzzy-finder-spec.js

Fixes #329
This replaces the existing logic which attempted to detect "internal symlinks". We simply keep a set of every inode number we have visited and make sure we don't visit the same node twice when traversing through symbolic links.

Track visited inodes in load-paths-handler to prevent looping

---

package.json

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
Brings in updated fuzzy sorting logic.
/cc @jeancroy
/cc @adamreisnz for testing.  Please let me know if you need help.  In addition, please tell me if you think #21 can be closed after this.  Thanks!

Update fuzzaldrin-plus to 0.6.0

---

lib/fuzzy-finder-view.js
spec/fuzzy-finder-spec.js

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
Only attempt to jump to a specific line number if the text after the colon is a valid line number.  Otherwise, show an error if appropriate and just jump to the file but don't change the cursor position.
None.
Line number validation and no more uncaught exceptions related to that.
None?
Fixes #308

Validate line numbers before jumping

---

spec/async-spec-helpers.js
spec/fuzzy-finder-spec.js

Modernizes the spec file to use async/await rather than waitsFor(Promise)/runs.

Use async/await in specs

---

lib/main.js

Doesn't leave commands hanging around after fuzzy-finder is deactivated, and also stops observing panes for changes.

Dispose of commands and callbacks when deactivating

---

lib/project-view.js
spec/project-view-spec.js

If teletype is installed and enabled, the file finder asks the teletype service for a list of remote editors:
https://github.com/atom/fuzzy-finder/blob/8c3c074f8dbff7a82b323c15af14889307dcf3b2/lib/project-view.js#L61
fuzzy-finder then iterates over the list of remote editors:
https://github.com/atom/fuzzy-finder/blob/8c3c074f8dbff7a82b323c15af14889307dcf3b2/lib/project-view.js#L62
However, it's [possible for `getRemoteEditors()` to return `null`](https://github.com/atom/teletype/blob/v0.10.0/lib/teletype-service.js#L12). When that happens, the file finder fails to show any _local_ files. Instead, it shows "Project is empty", and we see an error in the console:
This pull request teaches the fuzzy-finder to gracefully handle a null return value from `getRemoteEditors()`.
We could change …

Fix "Project is empty" issue when using Teletype

---

lib/fuzzy-finder-view.js
spec/fuzzy-finder-spec.js

As outlined in #358, the status message of the fuzzy finder did not update correctly while entering line numbers. This was due to an issue within the logic used to update the status message: The alert was not replaced by the standard message when the input became valid again because the `previousQueryWasLineJump` flag would stay true during the process, preventing the necessary block of code to be run.
The changes within this pull request fix this issue while simplifying the code in question a bit.
This is my first contribution to Atom, and I hope I did everything right. Do point me towards any mistakes I might have made though.
N/A
The fuzzy finder always displays an appropriate status message when entering line numbers, no longer misleading users.
N/A
#358

Correctly update the caption during line number entry

---

lib/fuzzy-finder-view.js
spec/fuzzy-finder-spec.js

#115
Previously, a user could request to jump to a specific line of a file or within the current editor by entering a colon followed by the line number into the fuzzy finder. This pull request enhances this feature by adding functionality to jump to a specific column within that line using a second colon. For example, `file.js:4:6` would open `file.js` and move the cursor to column six of line four. If the user has not specified a valid column number, Atom behaves in the same way as before the introduction of this enhancement and jumps to the first character within the specified line.
**Important Note:** I fixed a bug within the fuzzy finder status messages in pull request #359. These changes will need to be pulled into this pull request and adapted to the new functionality before …

Add feature to jump to columns within text lines

---

lib/fuzzy-finder-view.js
package-lock.json
spec/fuzzy-finder-spec.js

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
With #360, you can now specify a specific column when jumping to a line. The error reporting for invalid line numbers, however, was not updated to allow columns as well. This PR adds additional cases to the error handling such that it reports column errors correctly and does not inadvertently display "Invalid line number" when attempting to navigate to a column.
None.
An incorrect error is removed and there is better discoverability of the feature.
None.
Fixes #363, /cc @jtagscherer

Provide accurate error messages when jumping to columns

---

lib/load-paths-handler.js

Based on some profiling, the most expensive part of crawling the list of files is to check if each of the discovered files/folder are being ignored by `git` (the [`isIgnored()`](https://github.com/atom/fuzzy-finder/blob/master/lib/load-paths-handler.js#L37-L46)  method). This is done by calling the [`git-utils`](https://github.com/atom/git-utils) package which internally calls [`libgit2`](https://github.com/libgit2/libgit2/blob/635693d3bc55770ec7a6640ba3f2f0ee434a6042/src/ignore.c#L517).
For medium to large repos (>30K files), `isIgnored()` takes ~80-90% of the crawling time 💀.
Fortunately, the crawling logic is currently doing unnecessary checks to `isIgnored()`, which results in performing almost the double of checks than needed.
By removing the additional call to `isIgnored()` we can …

Remove unnecessary call to check if a path is ignored

---

lib/load-paths-handler.js
lib/path-loader.js
package-lock.json
package.json
spec/fuzzy-finder-spec.js

This PR contains some minimal changes to demonstrate the usage of `ripgrep` on the fuzzy finder, so we can discuss the tradeoffs and steps needed to be able to ship this.
This work comes as a follow-up from https://github.com/atom/fuzzy-finder/pull/367 after the suggestions of @smashwilson .
Using `ripgrep` speeds up drastically the time to crawl medium and large repositories (we're taking about **up to 14X faster times**):
| Type | Num Files | Time (master)  | Time (This PR) | Improvements  |
|---|---|---|---|---|
|  Small | 2K  | 1.3s  | 0.9s | **30%** less time (or **1.4X** faster)  🎉 |
|  Medium |  30K | 6.2s  | 1.2s  | **80%** less time (or **5X** faster) 🎉 |
|  Large | 270K  |  57.5s  |  4.1s  |  **93%** less time (or **14X** faster) 🎉 |
(the measurement has been done the same way …

Add option to use `ripgrep` for crawling the list of files

---

docs/events.md
lib/main.js
lib/path-loader.js
lib/project-view.js
lib/reporter-proxy.js
package.json
spec/fuzzy-finder-spec.js
spec/project-view-spec.js

This PR makes use of the `atom/metrics` package to be able to start logging the time it takes to index a project by the fuzzy finder.
The format of the data that's being logged is the following:
* **eventType**: `fuzzy-finder-v1`
* **metadata**
| field | value |
|-------|-------|
| `ec` | `time-to-crawl`
| `el` | Crawler type (`ripgrep` or `fs`)
| `ev` | Number of crawled files
Sample payload
```json
{
"eventType": "fuzzy-finder-v1",
"durationInMilliseconds": 539,
"metadata": {
"ec": "time-to-crawl",
"el": "ripgrep",
"ev": 49,
"cd2": "x64",
"cd3": "x64",
"cm1": 180,
"cm2": 83,
"sr": "1680x1050",
"vp": "1680x591",
"aiid": "dev"
},
"date": "2019-03-21T17:05:32.706Z"
}
```
Do not log this?
Knowing the time it takes to crawl the project by the fuzzy finder on real users will help us decide …

Start logging the time to index a project

---

lib/project-view.js
spec/fuzzy-finder-spec.js
spec/project-view-spec.js

This PR unblocks the work to use `native-fuzzy` to improve the filtering performance by mitigating one of [its concerns](https://github.com/atom/fuzzy-finder/issues/370#issuecomment-477246644).
Basically, before this PR the UI was blocked by the execution of the `setItems()` method every time the fuzzy finder was shown (and it delayed its appearance in the UI). This was not a big problem before because the `setItems()` method used to be quite fast, but with the addition of `native-fuzzy` we need to do more expensive things here (we need to serialize and pass the whole list of items to the `native-fuzzy`).
N/A
* Unblocking a big performance improvement.
* Less work done every time the fuzzy finder is opened
N/A
https://github.com/atom/fuzzy-finder/issues/370

Do not call `setItems()` every time that the fuzzy finder is shown

---

appveyor.yml
lib/fuzzy-finder-view.js
package-lock.json
package.json
spec/fuzzy-finder-spec.js

This PR does two things:
* Renames the `useAlternateScoring` config option to convert it to an enum called `scoringSystems` (using the same default value as before).
* Adds a new `scoringSystem` called `fast` (🤷‍♂️) which uses `fuzzy-native` to dramatically improve filtering times on large projects.
A few other options have been considered:
* Adding a debouncer without changing the current filtering logic.
* Keep the current filtering logic but move it to an async Task.
* Use the [`nuclide-prebuilt-libs`](https://github.com/facebook-atom/nuclide-prebuilt-libs) package instead of `fuzzy-native`.
* Create a new package with the `fuzzy-native` filtering logic executed in a background thread.
At the end, this solution is what IMHO gives more benefits and less tradeoffs per unit of effort 😅 …

Use `fuzzy-native` as an alternate scoring system

---

docs/events.md
lib/fuzzy-finder-view.js
lib/main.js
lib/project-view.js
lib/reporter-proxy.js
package-lock.json
package.json
spec/fuzzy-finder-spec.js

In order to understand better the real world performance of the `fuzzy-finder` and allow us to take better decisions, we want to start logging the time it takes to execute a filtering action.
Along with the time taken to do the filtering, we want to log some additional metadata:
* **Number of files in the repository**: the time will vary a lot depending on the project size so we need to be able to filter results by similar project sizes.
* **Scoring system**: Our hypothesis is that the new `fast` scoring system implemented [here](https://github.com/atom/fuzzy-finder/pull/374) will have an important impact on the filtering time, so we want to log which is the scoring type that's being used.
Since the `standard` scoring system is not controlled by the fuzzy finder (but via …

Add metrics for fuzzy-finder filtering time

---

spec/fuzzy-finder-spec.js

Sending this PR to check if it improves the flakiness reported in https://github.com/atom/atom/issues/19095

Return a promise instead of using waitsFor

---

docs/events.md
lib/experiment-prompt.js
lib/fuzzy-finder-view.js
lib/project-view.js
lib/reporter-proxy.js
lib/scoring-systems.js
styles/fuzzy-finder.less

This PR adds a prompt to the fuzzy finder which will inform users about the "fast mode" and will allow them to enable it easily.
In order to get the major benefits, the prompt will only be shown when opening large projects, and users will be able to disable the setting via the same prompt later.
More information in the associated task: https://github.com/atom/fuzzy-finder/issues/376
Things that need to be implemented still:
-  [x] Add logic to modify the user settings when clicking the notification.
https://github.com/atom/fuzzy-finder/issues/376

Show prompt to enable "fast mode" on large projects

---

lib/main.js

Closes #380
Since there were no tests introduced in #378, I've opted to just fix the bug and not add regression coverage.

Pass metricsReporter into GitStatusView to avoid null exception

---

lib/fuzzy-finder-view.js
spec/fuzzy-finder-spec.js

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
This PR fixes https://github.com/atom/fuzzy-finder/issues/382 by adding any root that contains a filter result to the list of final results. 
We could change `fuzzy-native` to accept an object that contains both the full path of the result (or an id) + the string to use for the matcher (as the standard fuzzy matcher does), but that would require sending a much bigger object to the native side which could slowdown thing (plus the change would be bigger and affect other repos).
Fixes https://github.com/atom/fuzzy-finder/issues/382
None that I can think of. …

Handle correctly similar results from multiple projects

---

lib/fuzzy-finder-view.js
package-lock.json
package.json
spec/fuzzy-finder-spec.js

🍐'd with @rafeca
Previously, limitations in the `fuzzy-native` API required us to call `fs.existsSync` on the main thread in order to map the relative paths in match results back into absolute paths in the presence of multiple project roots. This could block the main thread for an arbitrary amount of time and lead to performance degradation, so we decided to fix it.
The fix involved changing `fuzzy-native`'s API to associate each match candidate with an integer identifier. Currently, we're just assigning each item's id to its index in the items array. Now, when we get a match back from `fuzzy-native`, we can map it back to the original item that produced the candidate via the match's id. This removes the need for synchronous I/O to disambiguate the relative path.
I'd love to replace …

Eliminate synchronous I/O on main thread when displaying match results from fuzzy-native

---

lib/fuzzy-finder-view.js

In a similar way that https://github.com/atom/atom/pull/19272 fixed the scroll position after opening atom from the command line, this change does the same for the fuzzy finder. This way we have a consistent user experience for both scenarios.
The two main changes of this PR are:
* The selected line will get vertically centered in the editor.
* If the line is folder, it'll get unfolded.
**Before this change**
*With this change**
Do not do anything.
Consisten user experience when navigating to a line through the fuzzy finder.
N/A
https://github.com/atom/atom/issues/12253

Make sure that cursor position is centered after navigating to a line

---

lib/experiment-prompt.js
spec/buffer-view-spec.js
spec/fuzzy-finder-spec.js

This PR is a follow-up of https://github.com/atom/fuzzy-finder/pull/378 to get more people opting in to the fast mode.
Now that the fuzzy finder fast mode has been out for a couple of weeks in Atom v1.37 without any major issues, I’d like to open the gates a bit more to the feature to get more feedback from it before making it the default one.
The current plan is the following:
* **Atom v1.37:** Show prompt to enable it on large projects. (done)
* **Atom v1.38:** Show prompt to enable it on any project.
* **Atom v1.39:** Remove prompt and enable it by default.
Doing this will give us much more signal about the fast mode on Atom v1.38 before enabling it by default (since currently we only have ~0.5% of users with `ripgrep` enabled).
**Note**: Due to our release cadence, I'll need to …

Show fast mode prompt on any project size

---

lib/load-paths-handler.js
spec/fuzzy-finder-spec.js

This fixes a bug when experimental fast mode that uses ripgrep is enabled. Since excluding VCS ignored paths is the default behavior of ripgrep, option to not ignore them was not being passed when needed.
N/A
Excluding VCS ignored paths from fuzzy search will work a bit more consistently when using ripgrep.
N/A
N/A

Fix excluding VCS ignored paths based on the flag in core settings when ripgrep is enabled

---

package-lock.json

This includes:
* [A fix for a deprecation message on electron v3](https://github.com/atom/fs-plus/pull/46) in `fs-plus`.
---
- *List of changes between `fs-plus@3.0.2` and `fs-plus@3.1.1`: https://github.com/atom/fs-plus/compare/v3.0.2...v3.1.1*

⬆️ fs-plus@3.1.1

---

spec/fuzzy-finder-spec.js

This is an attempt to fix #386.
I worry that in cases where we are timing out, the attempt to listen might actually be producing an error, and we are simply dropping this error on the floor. If that is what's happening, we should now surface the error by rejecting the promise returned by the `beforeEach` block instead of just timing out in a `waitsFor` function.
I'm also waiting for the server to fully close in the `afterEach` block, just to be sure we stop listening before attempting to listen again. This seems unlikely, but it's more correct to wait for this anyway.

Avoid timeouts when listening on a socket in tests

---

lib/load-paths-handler.js
spec/fuzzy-finder-spec.js

Hi, this is my very first PR for Atom's core system ! 😁 
If an user's `core.ignoredNames` is modified so that it doesn't include `.git` or `.hg` (they are included by default) but still `core.excludeVcsIgnoredPaths` is `true`, then the new `fast` mode using `ripgrep` will show files in those directories (like `HEAD`, `COMMIT_EDITMSG` and so on).
Because those files are usually regarded as _VCS-ignored_ files and more over, the previous `alternative` mode does exclude those files when `core.excludeVcsIgnoredPaths` is `true`, I believe these files are better to be ignored in `fast` mode as well.
Please refer to https://github.com/atom/fuzzy-finder/issues/379#issuecomment-502635850 for more detail.
Only 5 line changes: Add `ripgrep` arguments to exclude those files when …

Ignore VCS directories even when they are not in ignoreNames

---

spec/fuzzy-finder-spec.js

This PR removes an assertion that's not actually needed in one of the `fuzzy-finder` specs. This assertion sometimes returns false (maybe because the crawler finishes too quickly) and was causing some failures.
This fixes https://github.com/atom/atom/issues/19581

Remove uneeded assertion in test

---

lib/experiment-prompt.js
package.json

Looks like we haven't got any major negative feedback during the opt-in period of the fast mode (more info [here](https://github.com/atom/fuzzy-finder/issues/379)), and the performance results are extremely positive from people opting in: **between 5X and 15X faster** depending on the project size:
Based on that, we've decided to make the fast mode the default mode on fuzzy finder and remove the opt-in prompt. We're going to leave the config options to allow user to revert to the old behaviour for a while, just to get some time for some potential obscure edge cases to pop out.
I'm planning to release a new version of the fuzzy finder once this PR gets merged and cherry pick the new version into the Atom v1.39 release

Make fast mode the default mode and remove prompt

---

package-lock.json
package.json

This new version includes support to matching directory separators using `_` or `\\` ([more info](https://github.com/atom/fuzzy-native/pull/6)).
----
*List of changes between `fuzzy-native@1.0.3` and `fuzzy-native@1.1.0`: https://github.com/atom/fuzzy-native/compare/v1.0.3...v1.1.0*

⬆️ @atom/fuzzy-native@1.1.0

---

lib/load-paths-handler.js
spec/fuzzy-finder-spec.js

When indexing a project with a lot of broken symbolic links, the indexing process never completes. This is because the `ripgrep` process has written more data to its error output (STDERR) than the calling process has buffer to receive; until this buffer is cleared, the process will not terminate. The solution to this is to process the data on the receiving side.
This pull request adds a simple no-op handler for anything sent back on STDERR from `ripgrep`.
I considered logging the error output from `ripgrep`. This produced a lot of noise when running the test-suite and is unlikely to be of use for anyone in the real world. Logging the error messages returned from `ripgrep` is a trivial change.
Indexing process always completes.
Diagnosing some issues may be difficult due to the lack of …

Consume STDERR from ripgrep to allow indexing process to complete

---

package-lock.json
package.json

removes the `-static-libstdc++` ld flag from binding.gyp and allows the package to dynamically bind to libstdc++ ([more info](https://github.com/atom/fuzzy-native/pull/7)).
----
*List of changes between `fuzzy-native@1.1.0` and `fuzzy-native@1.1.1`: https://github.com/atom/fuzzy-native/compare/v1.1.0...v1.1.1*

⬆️@atom/fuzzy-native@1.1.1
